// <auto-generated />
using System;
using AccionaCovid.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AccionaCovid.Data.Migrations
{
    [DbContext(typeof(AccionaCovidContext))]
    [Migration("20200504173315_PassportIsManual")]
    partial class PassportIsManual
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AccionaCovid.Domain.Model.AlertaEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("AlertaEmpleado");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.AlertaServiciosMedicos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("(N'')");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FechaNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("('0001-01-01T00:00:00.0000000+00:00')");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("Leido")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(0)))");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("(N'')");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("AlertaServiciosMedicos");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.Audits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int?>("KeyValues")
                        .HasColumnType("int");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.ColorEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ColorEstado");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<long>("IdWorkday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("(CONVERT([bigint],(0)))");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<long>("IdWorkday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("(CONVERT([bigint],(0)))");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Division");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Bloqueado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(0)))");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("EsServicioMedico")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(0)))");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Genero")
                        .HasColumnType("int");

                    b.Property<int?>("IdFichaLaboral")
                        .HasColumnType("int");

                    b.Property<int?>("IdFichaMedica")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioWorkDay")
                        .HasColumnType("int");

                    b.Property<bool?>("InterAcciona")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(0)))");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Nif")
                        .HasColumnName("NIF")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("UltimaModif")
                        .HasColumnType("datetime");

                    b.Property<string>("Upn")
                        .HasColumnName("UPN")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdFichaLaboral");

                    b.HasIndex("IdFichaMedica");

                    b.HasIndex("IdUsuarioWorkDay")
                        .HasName("IX_Empleado_IdUsuario");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.EmpleadoRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdRole");

                    b.ToTable("EmpleadoRole");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.EntregaEquipoProteccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdEquipoProteccion")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdEquipoProteccion");

                    b.ToTable("EntregaEquipoProteccion");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.EquipoProteccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EquipoProteccion");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.EstadoPasaporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("DiasValidez")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<int>("IdColorEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool?>("Pcrant")
                        .HasColumnName("PCRAnt")
                        .HasColumnType("bit");

                    b.Property<bool?>("Pcrult")
                        .HasColumnName("PCRUlt")
                        .HasColumnType("bit");

                    b.Property<bool?>("TestInmune")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdColorEstado");

                    b.HasIndex("IdTipoEstado");

                    b.ToTable("EstadoPasaporte");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.FactorRiesgo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FactorRiesgo");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.FichaLaboral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("IdDepartamento")
                        .HasColumnType("int");

                    b.Property<int>("IdDivision")
                        .HasColumnType("int");

                    b.Property<int>("IdLocalizacion")
                        .HasColumnType("int");

                    b.Property<int?>("IdLocalizacionAlter")
                        .HasColumnType("int");

                    b.Property<int?>("IdResponsableDirecto")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MailProf")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Obra")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("TelefonoCorp")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdDepartamento");

                    b.HasIndex("IdDivision");

                    b.HasIndex("IdLocalizacion");

                    b.HasIndex("IdResponsableDirecto");

                    b.ToTable("FichaLaboral");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.FichaMedica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("('0001-01-01T00:00:00.000')");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FichaMedica");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.Localizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Direccion1")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("(N'')")
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Localizacion");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.LocalizacionEmpleados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdLocalizacion")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdLocalizacion");

                    b.ToTable("LocalizacionEmpleados");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.ParametroMedico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("IdTipoParametro")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoParametro");

                    b.ToTable("ParametroMedico");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.Pasaporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Activo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(0)))");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaExpiracion")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("IdAccion")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoPasaporte")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsManual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(0)))");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdAccion");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdEstadoPasaporte");

                    b.ToTable("Pasaporte");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.ResultadoEncuestaSintomas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("IdFichaMedica")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoSintoma")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Valor")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdFichaMedica");

                    b.HasIndex("IdTipoSintoma");

                    b.ToTable("ResultadoEncuestaSintomas");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.ResultadoTestMedico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Control")
                        .HasColumnType("bit");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FechaTest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdFichaMedica")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<bool>("Igg")
                        .HasColumnName("IGG")
                        .HasColumnType("bit");

                    b.Property<bool>("Igm")
                        .HasColumnName("IGM")
                        .HasColumnType("bit");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdFichaMedica");

                    b.ToTable("ResultadoTestMedico");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.ResultadoTestPcr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FechaTest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdFichaMedica")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("Positivo")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdFichaMedica");

                    b.ToTable("ResultadoTestPCR");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.SeguimientoMedico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Activo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(0)))");

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FechaSeguimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdFichaMedica")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdFichaMedica");

                    b.ToTable("SeguimientoMedico");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.TipoEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoEstado");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.TipoParametroMedico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoParametroMedico");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.TipoSintomas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoSintomas");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.UsuarioWorkDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apellido2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<long>("Departamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("(CONVERT([bigint],(0)))");

                    b.Property<long>("Division")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("(CONVERT([bigint],(0)))");

                    b.Property<bool?>("EsServicioMedico")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(0)))");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Genero")
                        .HasColumnType("int");

                    b.Property<long?>("IdResponsable")
                        .HasColumnType("bigint");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<long>("IdWorkDay")
                        .HasColumnType("bigint");

                    b.Property<bool?>("InterAcciona")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(0)))");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Localizacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("MailCorporativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nif")
                        .HasColumnName("NIF")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("TelefonoCorporativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UltimaModif")
                        .HasColumnType("datetime");

                    b.Property<string>("Upn")
                        .HasColumnName("UPN")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UsuarioWorkDay");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.ValoracionFactorRiesgo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FechaFactor")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("IdFactorRiesgo")
                        .HasColumnType("int");

                    b.Property<int>("IdFichaMedica")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Valor")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdFactorRiesgo");

                    b.HasIndex("IdFichaMedica")
                        .HasName("IX_ValoracionFactorRiesgo_IdEvaluacionFactoresRiesgo");

                    b.ToTable("ValoracionFactorRiesgo");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.ValoracionParametroMedico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("IdParametroMedico")
                        .HasColumnType("int");

                    b.Property<int>("IdSegumientoMedico")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValueSql("(N'CREATE')")
                        .HasMaxLength(10);

                    b.Property<DateTime>("LastActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Valor")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdParametroMedico");

                    b.HasIndex("IdSegumientoMedico");

                    b.ToTable("ValoracionParametroMedico");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.AlertaEmpleado", b =>
                {
                    b.HasOne("AccionaCovid.Domain.Model.Empleado", "IdEmpleadoNavigation")
                        .WithMany("AlertaEmpleado")
                        .HasForeignKey("IdEmpleado")
                        .HasConstraintName("FK_AlertaEmpleado_Empleado")
                        .IsRequired();
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.AlertaServiciosMedicos", b =>
                {
                    b.HasOne("AccionaCovid.Domain.Model.Empleado", "IdEmpleadoNavigation")
                        .WithMany("AlertaServiciosMedicos")
                        .HasForeignKey("IdEmpleado")
                        .HasConstraintName("FK_AlertaServiciosMedicos_Empleado")
                        .IsRequired();
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.Empleado", b =>
                {
                    b.HasOne("AccionaCovid.Domain.Model.FichaLaboral", "IdFichaLaboralNavigation")
                        .WithMany("Empleado")
                        .HasForeignKey("IdFichaLaboral")
                        .HasConstraintName("FK_Empleado_FichaLaboral");

                    b.HasOne("AccionaCovid.Domain.Model.FichaMedica", "IdFichaMedicaNavigation")
                        .WithMany("Empleado")
                        .HasForeignKey("IdFichaMedica")
                        .HasConstraintName("FK_Empleado_FichaMedica");

                    b.HasOne("AccionaCovid.Domain.Model.UsuarioWorkDay", "IdUsuarioWorkDayNavigation")
                        .WithMany("Empleado")
                        .HasForeignKey("IdUsuarioWorkDay")
                        .HasConstraintName("FK_Empleado_UsuarioWorkDay")
                        .IsRequired();
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.EmpleadoRole", b =>
                {
                    b.HasOne("AccionaCovid.Domain.Model.Empleado", "IdEmpleadoNavigation")
                        .WithMany("EmpleadoRole")
                        .HasForeignKey("IdEmpleado")
                        .HasConstraintName("FK_EmpleadoRole_Empleado")
                        .IsRequired();

                    b.HasOne("AccionaCovid.Domain.Model.Role", "IdRoleNavigation")
                        .WithMany("EmpleadoRole")
                        .HasForeignKey("IdRole")
                        .HasConstraintName("FK_EmpleadoRole_Role")
                        .IsRequired();
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.EntregaEquipoProteccion", b =>
                {
                    b.HasOne("AccionaCovid.Domain.Model.Empleado", "IdEmpleadoNavigation")
                        .WithMany("EntregaEquipoProteccion")
                        .HasForeignKey("IdEmpleado")
                        .HasConstraintName("FK_EntregaEquipoProteccion_Empleado")
                        .IsRequired();

                    b.HasOne("AccionaCovid.Domain.Model.EquipoProteccion", "IdEquipoProteccionNavigation")
                        .WithMany("EntregaEquipoProteccion")
                        .HasForeignKey("IdEquipoProteccion")
                        .HasConstraintName("FK_EntregaEquipoProteccion_EquipoProteccion")
                        .IsRequired();
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.EstadoPasaporte", b =>
                {
                    b.HasOne("AccionaCovid.Domain.Model.ColorEstado", "IdColorEstadoNavigation")
                        .WithMany("EstadoPasaporte")
                        .HasForeignKey("IdColorEstado")
                        .HasConstraintName("FK_EstadoPasaporte_ColorEstado")
                        .IsRequired();

                    b.HasOne("AccionaCovid.Domain.Model.TipoEstado", "IdTipoEstadoNavigation")
                        .WithMany("EstadoPasaporte")
                        .HasForeignKey("IdTipoEstado")
                        .HasConstraintName("FK_EstadoPasaporte_TipoEstado")
                        .IsRequired();
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.FichaLaboral", b =>
                {
                    b.HasOne("AccionaCovid.Domain.Model.Departamento", "IdDepartamentoNavigation")
                        .WithMany("FichaLaboral")
                        .HasForeignKey("IdDepartamento")
                        .HasConstraintName("FK_FichaLaboral_Departamento")
                        .IsRequired();

                    b.HasOne("AccionaCovid.Domain.Model.Division", "IdDivisionNavigation")
                        .WithMany("FichaLaboral")
                        .HasForeignKey("IdDivision")
                        .HasConstraintName("FK_FichaLaboral_Division")
                        .IsRequired();

                    b.HasOne("AccionaCovid.Domain.Model.Localizacion", "IdLocalizacionNavigation")
                        .WithMany("FichaLaboral")
                        .HasForeignKey("IdLocalizacion")
                        .HasConstraintName("FK_FichaLaboral_Localizacion3")
                        .IsRequired();

                    b.HasOne("AccionaCovid.Domain.Model.Empleado", "IdResponsableDirectoNavigation")
                        .WithMany("FichaLaboral")
                        .HasForeignKey("IdResponsableDirecto")
                        .HasConstraintName("FK_FichaLaboral_Empleado");
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.LocalizacionEmpleados", b =>
                {
                    b.HasOne("AccionaCovid.Domain.Model.Empleado", "IdEmpleadoNavigation")
                        .WithMany("LocalizacionEmpleados")
                        .HasForeignKey("IdEmpleado")
                        .HasConstraintName("FK_LocalizacionEmpleados_Empleado")
                        .IsRequired();

                    b.HasOne("AccionaCovid.Domain.Model.Localizacion", "IdLocalizacionNavigation")
                        .WithMany("LocalizacionEmpleados")
                        .HasForeignKey("IdLocalizacion")
                        .HasConstraintName("FK_LocalizacionEmpleados_Localizacion")
                        .IsRequired();
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.ParametroMedico", b =>
                {
                    b.HasOne("AccionaCovid.Domain.Model.TipoParametroMedico", "IdTipoParametroNavigation")
                        .WithMany("ParametroMedico")
                        .HasForeignKey("IdTipoParametro")
                        .HasConstraintName("FK_ParametroMedico_TipoParametroMedico")
                        .IsRequired();
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.Pasaporte", b =>
                {
                    b.HasOne("AccionaCovid.Domain.Model.Empleado", "IdEmpleadoNavigation")
                        .WithMany("Pasaporte")
                        .HasForeignKey("IdEmpleado")
                        .HasConstraintName("FK_Pasaporte_Empleado")
                        .IsRequired();

                    b.HasOne("AccionaCovid.Domain.Model.EstadoPasaporte", "IdEstadoPasaporteNavigation")
                        .WithMany("Pasaporte")
                        .HasForeignKey("IdEstadoPasaporte")
                        .HasConstraintName("FK_Pasaporte_EstadoPasaporte")
                        .IsRequired();
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.ResultadoEncuestaSintomas", b =>
                {
                    b.HasOne("AccionaCovid.Domain.Model.FichaMedica", "IdFichaMedicaNavigation")
                        .WithMany("ResultadoEncuestaSintomas")
                        .HasForeignKey("IdFichaMedica")
                        .HasConstraintName("FK_ResultadoEncuestaSintomas_FichaMedica")
                        .IsRequired();

                    b.HasOne("AccionaCovid.Domain.Model.TipoSintomas", "IdTipoSintomaNavigation")
                        .WithMany("ResultadoEncuestaSintomas")
                        .HasForeignKey("IdTipoSintoma")
                        .HasConstraintName("FK_ResultadoEncuestaSintomas_TipoSintomas")
                        .IsRequired();
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.ResultadoTestMedico", b =>
                {
                    b.HasOne("AccionaCovid.Domain.Model.FichaMedica", "IdFichaMedicaNavigation")
                        .WithMany("ResultadoTestMedico")
                        .HasForeignKey("IdFichaMedica")
                        .HasConstraintName("FK_ResultadoTestMedico_FichaMedica")
                        .IsRequired();
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.ResultadoTestPcr", b =>
                {
                    b.HasOne("AccionaCovid.Domain.Model.FichaMedica", "IdFichaMedicaNavigation")
                        .WithMany("ResultadoTestPcr")
                        .HasForeignKey("IdFichaMedica")
                        .HasConstraintName("FK_ResultadoTestPCR_FichaMedica")
                        .IsRequired();
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.SeguimientoMedico", b =>
                {
                    b.HasOne("AccionaCovid.Domain.Model.FichaMedica", "IdFichaMedicaNavigation")
                        .WithMany("SeguimientoMedico")
                        .HasForeignKey("IdFichaMedica")
                        .HasConstraintName("FK_SeguimientoMedico_FichaMedica")
                        .IsRequired();
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.ValoracionFactorRiesgo", b =>
                {
                    b.HasOne("AccionaCovid.Domain.Model.FactorRiesgo", "IdFactorRiesgoNavigation")
                        .WithMany("ValoracionFactorRiesgo")
                        .HasForeignKey("IdFactorRiesgo")
                        .HasConstraintName("FK_ValoracionFactorRiesgo_FactorRiesgo")
                        .IsRequired();

                    b.HasOne("AccionaCovid.Domain.Model.FichaMedica", "IdFichaMedicaNavigation")
                        .WithMany("ValoracionFactorRiesgo")
                        .HasForeignKey("IdFichaMedica")
                        .HasConstraintName("FK_ValoracionFactorRiesgo_FichaMedica")
                        .IsRequired();
                });

            modelBuilder.Entity("AccionaCovid.Domain.Model.ValoracionParametroMedico", b =>
                {
                    b.HasOne("AccionaCovid.Domain.Model.ParametroMedico", "IdParametroMedicoNavigation")
                        .WithMany("ValoracionParametroMedico")
                        .HasForeignKey("IdParametroMedico")
                        .HasConstraintName("FK_ValoracionParametroMedico_ParametroMedico")
                        .IsRequired();

                    b.HasOne("AccionaCovid.Domain.Model.SeguimientoMedico", "IdSegumientoMedicoNavigation")
                        .WithMany("ValoracionParametroMedico")
                        .HasForeignKey("IdSegumientoMedico")
                        .HasConstraintName("FK_ValoracionParametroMedico_SeguimientoMedico")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
