//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccionaCovid.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidatorFields {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidatorFields() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccionaCovid.Application.Resources.ValidatorFields", typeof(ValidatorFields).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alerta.
        /// </summary>
        internal static string Alerta {
            get {
                return ResourceManager.GetString("Alerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentario.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días de validez.
        /// </summary>
        internal static string DiasValidez {
            get {
                return ResourceManager.GetString("DiasValidez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a División.
        /// </summary>
        internal static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DNI.
        /// </summary>
        internal static string DNI {
            get {
                return ResourceManager.GetString("DNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empleado.
        /// </summary>
        internal static string Empleado {
            get {
                return ResourceManager.GetString("Empleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factores de riesgo.
        /// </summary>
        internal static string FactoresRiesgo {
            get {
                return ResourceManager.GetString("FactoresRiesgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ficha Médica.
        /// </summary>
        internal static string FichaMedica {
            get {
                return ResourceManager.GetString("FichaMedica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtro.
        /// </summary>
        internal static string Filtro {
            get {
                return ResourceManager.GetString("Filtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador del color.
        /// </summary>
        internal static string IdColor {
            get {
                return ResourceManager.GetString("IdColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador del dispositivo.
        /// </summary>
        internal static string IdDispositivo {
            get {
                return ResourceManager.GetString("IdDispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador del empleado.
        /// </summary>
        internal static string IdEmpleado {
            get {
                return ResourceManager.GetString("IdEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador del estado del pasaporte.
        /// </summary>
        internal static string IdEstadoPasaporte {
            get {
                return ResourceManager.GetString("IdEstadoPasaporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador de la monitorización médica.
        /// </summary>
        internal static string IdMonitorizacionMedica {
            get {
                return ResourceManager.GetString("IdMonitorizacionMedica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador del responsable.
        /// </summary>
        internal static string IdResponsable {
            get {
                return ResourceManager.GetString("IdResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador del test PCR.
        /// </summary>
        internal static string IdTestPCR {
            get {
                return ResourceManager.GetString("IdTestPCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador del text rápido.
        /// </summary>
        internal static string IdTestRapido {
            get {
                return ResourceManager.GetString("IdTestRapido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de parametros.
        /// </summary>
        internal static string ListaParametros {
            get {
                return ResourceManager.GetString("ListaParametros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Localización.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetro Médico.
        /// </summary>
        internal static string MedicalParameter {
            get {
                return ResourceManager.GetString("MedicalParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre en inglés.
        /// </summary>
        internal static string NombreEN {
            get {
                return ResourceManager.GetString("NombreEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre en español.
        /// </summary>
        internal static string NombreES {
            get {
                return ResourceManager.GetString("NombreES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pais.
        /// </summary>
        internal static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pasaporte.
        /// </summary>
        internal static string Passport {
            get {
                return ResourceManager.GetString("Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado del pasaporte.
        /// </summary>
        internal static string PassportState {
            get {
                return ResourceManager.GetString("PassportState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test PCR.
        /// </summary>
        internal static string PcrTest {
            get {
                return ResourceManager.GetString("PcrTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Test Rápido.
        /// </summary>
        internal static string QuickTest {
            get {
                return ResourceManager.GetString("QuickTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de síntoma.
        /// </summary>
        internal static string TipoSintoma {
            get {
                return ResourceManager.GetString("TipoSintoma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
    }
}
